version: "3.5"

services:
  db:
    image: mariadb:10.7
    container_name: pichome-db  # 容器名称
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    # 无需暴露端口, 直接使用数据库内部IP地址: docker inspect pichome-db | grep IPAddress
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_PASSWORD=yrN5rUcP233QHdnU"
      - "MYSQL_DATABASE_FILE=/run/secrets/mysql_db"
      - "MYSQL_USER_FILE=/run/secrets/mysql_user"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mysql_password"
    restart: always
    secrets:
      - mysql_db
      - mysql_password
      - mysql_user

  app:
    image: oaooa/pichome
    container_name: pichome  # 容器名称
    # 无需暴露端口, 使用nginx stream 转发到内部IP地址: docker inspect pichome | grep IPAddress
    links:
      - db
    volumes:
      - "./site:/var/www/html"
      - "/mnt/sdb/data/soft_db/eagle:/mnt/eagle"  # eagle数据库路径映射
    environment:
      - "MYSQL_SERVER=db"
      - "MYSQL_DATABASE_FILE=/run/secrets/mysql_db"
      - "MYSQL_USER_FILE=/run/secrets/mysql_user"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mysql_password"
    restart: always
    secrets:
      - mysql_db
      - mysql_password
      - mysql_user

secrets:
  mysql_db:
    file: "./mysql_db.txt"
  mysql_password:
    file: "./mysql_password.txt"
  mysql_user:
    file: "./mysql_user.txt"
